# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import clock_pb2 as proto_dot_clock__pb2


class ClockSyncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sync = channel.unary_unary(
                '/clock.ClockSync/Sync',
                request_serializer=proto_dot_clock__pb2.SyncRequest.SerializeToString,
                response_deserializer=proto_dot_clock__pb2.SyncResponse.FromString,
                )
        self.GetTime = channel.unary_unary(
                '/clock.ClockSync/GetTime',
                request_serializer=proto_dot_clock__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=proto_dot_clock__pb2.TimeInfo.FromString,
                )
        self.UpdateTime = channel.unary_unary(
                '/clock.ClockSync/UpdateTime',
                request_serializer=proto_dot_clock__pb2.UpdateTimeRequest.SerializeToString,
                response_deserializer=proto_dot_clock__pb2.UpdateTimeResponse.FromString,
                )


class ClockSyncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClockSyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=proto_dot_clock__pb2.SyncRequest.FromString,
                    response_serializer=proto_dot_clock__pb2.SyncResponse.SerializeToString,
            ),
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=proto_dot_clock__pb2.GetTimeRequest.FromString,
                    response_serializer=proto_dot_clock__pb2.TimeInfo.SerializeToString,
            ),
            'UpdateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTime,
                    request_deserializer=proto_dot_clock__pb2.UpdateTimeRequest.FromString,
                    response_serializer=proto_dot_clock__pb2.UpdateTimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clock.ClockSync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClockSync(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clock.ClockSync/Sync',
            proto_dot_clock__pb2.SyncRequest.SerializeToString,
            proto_dot_clock__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clock.ClockSync/GetTime',
            proto_dot_clock__pb2.GetTimeRequest.SerializeToString,
            proto_dot_clock__pb2.TimeInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clock.ClockSync/UpdateTime',
            proto_dot_clock__pb2.UpdateTimeRequest.SerializeToString,
            proto_dot_clock__pb2.UpdateTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
